import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { LegalHeader, Section, LegalList, Contact } from "@/components/legal/prose";

export const metadata: Metadata = {
  title: "Privacy Policy — CxOPack",
  description: "What data CxOPack collects, how it's used, and your rights under GDPR.",
};

const LAST_UPDATED = "20 April 2026";

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <article>
      <LegalHeader
        title="Privacy Policy"
        lastUpdated={LAST_UPDATED}
        summary="We collect as little data as possible, use it only to run the service, and give you full control under GDPR. This page explains exactly what, how, and with whom."
      />

      <Section id="controller" title="1. Data Controller">
        <p>
          The data controller is <strong>Abdeldjalil Sichaib</strong>, operating CxOPack as a sole
          proprietor based in France. Contact: <code>hello@cxopack.com</code>. For security-related
          matters: <code>security@cxopack.com</code>.
        </p>
      </Section>

      <Section id="data-collected" title="2. Data we collect">
        <p>We collect only data necessary to provide the service:</p>
        <LegalList>
          <li>
            <strong>Account + billing data</strong> — email address, name (if provided), billing
            country, VAT identifier (if applicable). Collected at checkout through Stripe.
          </li>
          <li>
            <strong>GitHub username</strong> — provided by you at checkout so we can invite you to
            the private kit repositories.
          </li>
          <li>
            <strong>Transaction data</strong> — plan purchased, amount, date, Stripe session and
            subscription identifiers. Stored in our database.
          </li>
          <li>
            <strong>Communication data</strong> — emails you send us, with their content, so we can
            reply.
          </li>
          <li>
            <strong>Waitlist entries</strong> — if you join the Autopilot waitlist, we store your
            email address and the source of the signup.
          </li>
          <li>
            <strong>Technical data</strong> — server logs (IP address, user agent, timestamps) for
            security and abuse prevention. Retained for 30 days.
          </li>
        </LegalList>
        <p>
          We do <strong>not</strong> collect: payment card numbers (handled directly by Stripe),
          data from your installed Kits (they run locally in your AI tool), or personal content
          generated by your use of the Kits (such content stays on your machine).
        </p>
      </Section>

      <Section id="purposes" title="3. Why we use it">
        <LegalList>
          <li>To provide the service (create your order, grant repository access, send invoices).</li>
          <li>To send transactional emails (welcome, renewal reminders, cancellation confirmations).</li>
          <li>
            To send occasional product updates — only to active customers, and only with an easy
            one-click unsubscribe.
          </li>
          <li>To comply with legal obligations (invoicing, tax reporting).</li>
          <li>To prevent abuse and enforce the Terms of Service.</li>
        </LegalList>
        <p>
          Legal basis under GDPR: <strong>contract</strong> for transactional processing,{" "}
          <strong>legitimate interest</strong> for security and abuse prevention,{" "}
          <strong>consent</strong> for non-transactional marketing emails (which you can withdraw
          anytime).
        </p>
      </Section>

      <Section id="processors" title="4. Third-party processors">
        <p>
          We use a small number of trusted processors. Each handles specific data under their own
          privacy policies (linked below):
        </p>
        <LegalList>
          <li>
            <strong>Stripe</strong> (Ireland / US) — payment processing, invoicing, tax
            calculation. Handles your billing details and card data.
            <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="ml-2 text-[var(--color-brand)] underline decoration-dotted underline-offset-4">Policy</a>
          </li>
          <li>
            <strong>Supabase</strong> (EU region) — our database host. Stores orders, entitlements,
            waitlist entries.
            <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="ml-2 text-[var(--color-brand)] underline decoration-dotted underline-offset-4">Policy</a>
          </li>
          <li>
            <strong>Resend</strong> (US) — transactional email delivery. Sends welcome emails,
            renewal reminders, and cancellation confirmations.
            <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="ml-2 text-[var(--color-brand)] underline decoration-dotted underline-offset-4">Policy</a>
          </li>
          <li>
            <strong>Vercel</strong> (US) — hosts the landing page and API. Handles request logs.
            <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="ml-2 text-[var(--color-brand)] underline decoration-dotted underline-offset-4">Policy</a>
          </li>
          <li>
            <strong>GitHub</strong> (US) — hosts private repositories and issues customer
            invitations. We pass only your GitHub username and organisation-level metadata.
            <a href="https://docs.github.com/en/site-policy/privacy-policies" target="_blank" rel="noopener noreferrer" className="ml-2 text-[var(--color-brand)] underline decoration-dotted underline-offset-4">Policy</a>
          </li>
        </LegalList>
        <p>
          Transfers outside the EU (to the US) are governed by Standard Contractual Clauses signed
          with each processor.
        </p>
      </Section>

      <Section id="cookies" title="5. Cookies and analytics">
        <p>
          The site uses essential cookies only — for authentication state and Stripe checkout
          functionality. We do not currently use marketing cookies or third-party advertising
          trackers.
        </p>
        <p>
          If we introduce analytics in the future (e.g. privacy-first tools like Plausible), we
          will update this policy and notify active customers in advance.
        </p>
      </Section>

      <Section id="retention" title="6. Retention">
        <LegalList>
          <li>
            <strong>Account and transactional data</strong>: retained for the duration of your
            subscription plus 10 years after your last transaction (French accounting law).
          </li>
          <li>
            <strong>Server logs</strong>: 30 days.
          </li>
          <li>
            <strong>Waitlist entries</strong>: until you opt out, or up to 24 months of inactivity,
            whichever comes first.
          </li>
          <li>
            <strong>Email communication</strong>: retained while we have an active relationship with
            you.
          </li>
        </LegalList>
      </Section>

      <Section id="rights" title="7. Your rights (GDPR)">
        <p>If you are in the EU, UK, Switzerland, or any jurisdiction granting equivalent rights, you have the right to:</p>
        <LegalList>
          <li>Access the personal data we hold about you.</li>
          <li>Correct inaccurate data.</li>
          <li>Request deletion (subject to legal retention obligations).</li>
          <li>Export your data in a portable format.</li>
          <li>Object to processing, or restrict it.</li>
          <li>Withdraw consent for non-essential processing.</li>
          <li>Lodge a complaint with the CNIL (France) or your local data protection authority.</li>
        </LegalList>
        <p>
          To exercise any of these rights, email <code>hello@cxopack.com</code>. We respond within
          30 days.
        </p>
      </Section>

      <Section id="security" title="8. Security">
        <p>
          We follow reasonable technical and organisational measures to protect your data:
          encryption in transit (HTTPS / TLS), encryption at rest on Supabase, access control via
          GitHub and Supabase Auth, quarterly secrets rotation, and least-privilege access to all
          internal tooling.
        </p>
        <p>
          No system is perfectly secure. If we become aware of a breach affecting your data, we
          will notify affected customers within 72 hours of confirmation as required by GDPR
          Article 33.
        </p>
      </Section>

      <Section id="children" title="9. Children">
        <p>
          CxOPack is a professional tool not intended for anyone under the age of 16. We do not
          knowingly collect data from minors. If you believe a minor has submitted data to us,
          contact <code>hello@cxopack.com</code> and we will delete it.
        </p>
      </Section>

      <Section id="changes" title="10. Changes to this policy">
        <p>
          We may update this policy to reflect legal or operational changes. Material changes will
          be announced by email to active customers at least 30 days before taking effect. The
          current version is always available at <code>cxopack.com/legal/privacy</code>.
        </p>
      </Section>

      <Section id="contact" title="11. Contact">
        <Contact />
      </Section>
    </article>
  );
}
