/**
 * Pricing v2 (Edition I → II):
 *  - 5 single kits at €49 lifetime each
 *  - All-Access Pass: €149/yr subscription
 *  - Launch 100 All-Access: €99/yr subscription, locked for life (first 100 only)
 *
 * Old SKUs (Full Pack €299, Founding 100 €249, Club M/Y) are no longer created.
 * Archive them manually in the Stripe dashboard.
 *
 * Usage: STRIPE_SECRET_KEY=sk_test_… pnpm setup:stripe
 */

import Stripe from "stripe";
import { writeFileSync } from "node:fs";

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
  console.error("Missing STRIPE_SECRET_KEY env var.");
  process.exit(1);
}

const stripe = new Stripe(key, { apiVersion: "2024-12-18.acacia" as Stripe.LatestApiVersion });

type Spec =
  | { envKey: string; name: string; description: string; amount: number; recurring?: never }
  | { envKey: string; name: string; description: string; amount: number; recurring: "month" | "year" };

const SPECS: Spec[] = [
  // Single kits — €49 lifetime
  { envKey: "STRIPE_PRICE_KIT_CEO",   name: "CxOPack CEO Kit",   description: "Strategic co-founder workflows.", amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CTO",   name: "CxOPack CTO Kit",   description: "Tech co-founder workflows.",       amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CFO",   name: "CxOPack CFO Kit",   description: "Finance co-founder workflows.",    amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_SALES", name: "CxOPack Sales Kit", description: "Head of sales workflows.",         amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CMO",   name: "CxOPack CMO Kit",   description: "Head of marketing workflows.",     amount: 4900 },

  // All-Access Pass — every current + future kit, the Board, monthly drops, community
  { envKey: "STRIPE_PRICE_ALL_ACCESS_YEARLY", name: "CxOPack All-Access Pass", description: "Every current + future kit, The Board, monthly drops, community.", amount: 14900, recurring: "year" },

  // Launch 100 — same All-Access value at a forever-locked discount; first 100 buyers only
  { envKey: "STRIPE_PRICE_LAUNCH_100_YEARLY", name: "CxOPack All-Access Pass — Launch 100", description: "First 100 only. €99/yr forever, never increases.", amount: 9900, recurring: "year" },
];

async function main() {
  const env: string[] = ["# Generated by scripts/setup-stripe.ts (v2)"];

  for (const s of SPECS) {
    const product = await stripe.products.create({
      name: s.name,
      description: s.description,
    });
    const price = await stripe.prices.create({
      product: product.id,
      currency: "eur",
      unit_amount: s.amount,
      ...(s.recurring ? { recurring: { interval: s.recurring } } : {}),
    });
    env.push(`${s.envKey}=${price.id}`);
    console.log(`✓ ${s.name} → ${price.id}`);
  }

  writeFileSync(".env.stripe", env.join("\n") + "\n");
  console.log("\nWrote .env.stripe — copy into .env.local and Vercel env.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
