/**
 * One-shot script: creates all 9 Stripe products, prices, and writes IDs to a `.env.stripe` file.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_test_… pnpm tsx scripts/setup-stripe.ts
 *
 * Then copy `.env.stripe` contents into your `.env.local` and Vercel env.
 */

import Stripe from "stripe";
import { writeFileSync } from "node:fs";

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
  console.error("Missing STRIPE_SECRET_KEY env var.");
  process.exit(1);
}

const stripe = new Stripe(key, { apiVersion: "2024-12-18.acacia" as Stripe.LatestApiVersion });

type Spec =
  | { envKey: string; name: string; description: string; amount: number; recurring?: never }
  | { envKey: string; name: string; description: string; amount: number; recurring: "month" | "year" };

const SPECS: Spec[] = [
  { envKey: "STRIPE_PRICE_KIT_CEO", name: "CxOPack CEO Kit", description: "Strategic co-founder workflows.", amount: 9900 },
  { envKey: "STRIPE_PRICE_KIT_CTO", name: "CxOPack CTO Kit", description: "Tech co-founder workflows.", amount: 9900 },
  { envKey: "STRIPE_PRICE_KIT_CFO", name: "CxOPack CFO Kit", description: "Finance co-founder workflows.", amount: 9900 },
  { envKey: "STRIPE_PRICE_KIT_SALES", name: "CxOPack Sales Kit", description: "Head of sales workflows.", amount: 9900 },
  { envKey: "STRIPE_PRICE_KIT_CMO", name: "CxOPack CMO Kit", description: "Head of marketing workflows.", amount: 9900 },
  { envKey: "STRIPE_PRICE_FULL_PACK", name: "CxOPack Full Pack", description: "All 5 kits.", amount: 29900 },
  { envKey: "STRIPE_PRICE_FOUNDING_100", name: "CxOPack Founding 100", description: "First 100 Full Pack buyers — discount + testimonial.", amount: 24900 },
  { envKey: "STRIPE_PRICE_CLUB_MONTHLY", name: "CxOPack Founder's Club (monthly)", description: "Full Pack + monthly drops + community + live call.", amount: 4900, recurring: "month" },
  { envKey: "STRIPE_PRICE_CLUB_YEARLY", name: "CxOPack Founder's Club (yearly)", description: "Full Pack + monthly drops + community + live call.", amount: 39900, recurring: "year" },
];

async function main() {
  const env: string[] = ["# Generated by scripts/setup-stripe.ts"];

  for (const s of SPECS) {
    const product = await stripe.products.create({
      name: s.name,
      description: s.description,
    });
    const price = await stripe.prices.create({
      product: product.id,
      currency: "eur",
      unit_amount: s.amount,
      ...(s.recurring ? { recurring: { interval: s.recurring } } : {}),
    });
    env.push(`${s.envKey}=${price.id}`);
    console.log(`✓ ${s.name} → ${price.id}`);
  }

  writeFileSync(".env.stripe", env.join("\n") + "\n");
  console.log("\nWrote .env.stripe — copy these lines into .env.local and Vercel env.");
  console.log("\nDon't forget to create a webhook in Stripe Dashboard pointing to /api/stripe/webhook.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
