/**
 * LIVE-MODE Stripe setup — creates real, billable products and prices.
 *
 * Safety guards:
 *  1. Requires STRIPE_SECRET_KEY starting with `sk_live_`.
 *  2. Requires CONFIRM=YES env var to actually run (prevents accidental execution).
 *  3. Lists existing live products first — if any CxOPack product already exists,
 *     aborts unless FORCE=YES is also set (prevents duplicate creation).
 *  4. Writes to `.env.stripe.live` (not `.env.stripe`) so you can diff before
 *     copying into Vercel production env.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_live_… CONFIRM=YES pnpm setup:stripe:live
 *
 * Pricing (same as test): 5 kits @ €49 lifetime, All-Access €149/yr, Launch-100 €99/yr.
 */

import Stripe from "stripe";
import { writeFileSync, existsSync } from "node:fs";

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
  console.error("✗ Missing STRIPE_SECRET_KEY env var.");
  process.exit(1);
}
if (!key.startsWith("sk_live_")) {
  console.error("✗ STRIPE_SECRET_KEY must start with sk_live_ for this script.");
  console.error("  Use scripts/setup-stripe.ts for test mode.");
  process.exit(1);
}
if (process.env.CONFIRM !== "YES") {
  console.error("✗ This script creates LIVE, BILLABLE products in Stripe.");
  console.error("  Re-run with CONFIRM=YES to proceed.");
  process.exit(1);
}

const stripe = new Stripe(key, { apiVersion: "2024-12-18.acacia" as Stripe.LatestApiVersion });

type Spec =
  | { envKey: string; name: string; description: string; amount: number; recurring?: never }
  | { envKey: string; name: string; description: string; amount: number; recurring: "month" | "year" };

const SPECS: Spec[] = [
  { envKey: "STRIPE_PRICE_KIT_CEO",   name: "CxOPack — Harvey · CEO Kit",        description: "Strategic co-founder workflows. Closer mentality.", amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CTO",   name: "CxOPack — Elliot · CTO Kit",        description: "Tech co-founder workflows. Anti-bullshit.",         amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CFO",   name: "CxOPack — Axe · CFO Kit",           description: "Finance co-founder workflows. Bear-case default.",  amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_SALES", name: "CxOPack — Ari · Head of Sales Kit", description: "Head of sales workflows. Pushes for the meeting.",  amount: 4900 },
  { envKey: "STRIPE_PRICE_KIT_CMO",   name: "CxOPack — Don · CMO Kit",           description: "Head of marketing workflows. Story over features.", amount: 4900 },
  { envKey: "STRIPE_PRICE_ALL_ACCESS_YEARLY", name: "CxOPack All-Access Pass", description: "Every current + future kit, The Board, monthly drops, community.", amount: 14900, recurring: "year" },
  { envKey: "STRIPE_PRICE_LAUNCH_100_YEARLY", name: "CxOPack All-Access Pass — Launch 100", description: "First 100 only. €99/yr forever, never increases.", amount: 9900, recurring: "year" },
];

async function checkExisting() {
  const existing = await stripe.products.list({ limit: 100, active: true });
  const cxopack = existing.data.filter((p) => p.name.startsWith("CxOPack"));
  if (cxopack.length > 0 && process.env.FORCE !== "YES") {
    console.error(`✗ Found ${cxopack.length} existing CxOPack product(s) in live mode:`);
    for (const p of cxopack) console.error(`  · ${p.name} (${p.id})`);
    console.error("\nArchive them in the Stripe dashboard or re-run with FORCE=YES.");
    process.exit(1);
  }
}

async function main() {
  console.log("▶ Live-mode Stripe setup. Checking existing products…");
  await checkExisting();

  if (existsSync(".env.stripe.live")) {
    console.error("✗ .env.stripe.live already exists. Rename or delete it first.");
    process.exit(1);
  }

  const env: string[] = [
    "# Generated by scripts/setup-stripe-live.ts",
    `# ${new Date().toISOString()}`,
    "# Copy these into Vercel Production env (not Preview, not Development).",
  ];

  for (const s of SPECS) {
    const product = await stripe.products.create({
      name: s.name,
      description: s.description,
    });
    const price = await stripe.prices.create({
      product: product.id,
      currency: "eur",
      unit_amount: s.amount,
      ...(s.recurring ? { recurring: { interval: s.recurring } } : {}),
    });
    env.push(`${s.envKey}=${price.id}`);
    console.log(`✓ ${s.name} → ${price.id}`);
  }

  writeFileSync(".env.stripe.live", env.join("\n") + "\n");
  console.log("\n▶ Wrote .env.stripe.live");
  console.log("  Next: paste these into Vercel Production env + rotate STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET to live.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
